#include "../include/jsonpg.h"
#include "common.h"
#include "types.h"
#include "generate.h"
#include "dom.h"
#include "fast_double_parser.h"

//#define JSONPG_DEBUG
#include "debug.c"
#include "dragonbox.c"
#include "itoa.c"
#include "alloc.c"
#include "utf8.c"
#include "input_stream.c"
#include "error.c"
#include "output_stream.c"
#include "stack.c"
#include "generate.c"
#include "dom.c"
#include "parser.c"
#include "parse.c"
#include "parse_next.c"

